services:
  sanic:
    build:
      context: ./application
      args:
        REQUIREMENTS: local.txt
    command: sanic server:app --host=0.0.0.0 --port=5000 --workers=2 --dev --reload
    
    env_file:
      .env
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT:-5000}:5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongodb_data_container:/data/db
  
  mongo-testing:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - ${MONGO_TESTING_PORT:-27018}:27017
    
volumes:
  mongodb_data_container: